# Generated by Django 5.0.8 on 2024-09-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.CharField(db_index=True, max_length=128)),
                ('status', models.IntegerField(choices=[(-2, 'Stopped'), (-1, 'Blocked'), (0, 'Initial'), (1, 'Running'), (2, 'Done')], db_index=True, default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='BatchCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'CREATE'), (1, 'ADD'), (2, 'REMOVE'), (3, 'MERGE')], default=0)),
                ('index', models.IntegerField()),
                ('json', models.JSONField()),
                ('status', models.IntegerField(choices=[(-1, 'Error'), (0, 'Initial'), (1, 'Running'), (2, 'Done')], db_index=True, default=0)),
                ('raw', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('data_type_verified', models.BooleanField(default=False)),
                ('response_json', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.batch')),
            ],
            options={
                'verbose_name': 'Batch Command',
                'verbose_name_plural': 'Batch Commands',
                'index_together': {('batch', 'index')},
            },
        ),
    ]
